name: Enkaptic
description: Anthony Smith's software site
url: http://www.enkaptic.co.uk
exclude: [README.md]
permalink: /:year/:month/:day/:title/
paginate: 10
paginate_path: "page/:num/"
excerpt_separator: '' # https://github.com/jekyll/jekyll/issues/1401