name: Enkaptic
description: Anthony Smith's Software Site
url: http://enkaptic.co.uk
markdown: redcarpet
pygments: true
exclude: [README.md]
permalink: /:year/:month/:day/:title/
paginate: 10
paginate_path: "page/:num/"